require('lspkind').init({
    with_text = true,
    preset = 'codicons',
		symbol_map = {
      Text = '  ',
      Method = '  ',
      Function = '  ',
      Constructor = '  ',
      Variable = '﵁',
      Class = '  ',
      Interface = ' 蘒',
      Module = '  ',
      Property = '  ',
      Unit = '  ',
      Value = '  ',
      Enum = ' ',
      Keyword = '  ',
      Snippet = '  ',
      Color = '',
      File = '',
      Folder = ' ﱮ ',
      EnumMember = '  ',
      Constant = ' ﬦ ',
      Struct = '  '
    },
})
